module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      full: { max: "320px" },
      xs: "0px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xxl: "1536px",
    },
    maxWidth: {
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75%",
      full: "100%",
      max: "max-content",
    },
    colors: {
      primary: "var(--primary-color)",
      secondary: "var(--secondary-color)",
      shadow: "var(--shadow-color)",
      danger: "var(--danger-color)",
      warning: "var(--warning-color)",
      success: "var(--success-color)",
      info: "var(--info-color)",
      light: "var(--light-color)",
      gray: "var(--gray-color)",
      discord: "var(--discord-color)",
      white: "var(--white)",
    },
    borderRadius: {
      none: "0px",
      sm: "0.125rem",
      DEFAULT: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "30px",
      "3xl": "50px",
      full: "9999px",
    },
    spacing: {
      default: "0.375rem 0.75rem",
      small: "0.19rem 0.375rem",
      large: "0.75rem 1.5rem",
      0: "0px",
      1: "1px",
      2: "2px",
      3: "3px",
      6: "6px",
      8: "8px",
      10: "10px",
      12: "12px",
      16: "16px",
      24: "24px",
      32: "32px",
      36: "36px",
      40: "40px",
      48: "48px",
      54: "54px",
      76: "76px",
      95: "95px",
      200: "200px",
    },
    zIndex: {},
    fontFamily: {
      primary: "IBM Plex Sans",
      secondary: "Roboto",
    },
    fontSize: {
      14: "14px",
      16: "16px",
      18: "18px",
      24: "24px",
      36: "36px",
      h1: "72px",
      h2: "50px",
      h3: "46px",
      h4: "30px",
      h5: "12px",
      h6: "20px",
      ind: "35px",
    },
    letterSpacing: {},
  },

  variants: {
    extend: {
      textColor: ["visited"],
    },
  },
  plugins: [],
};
